
//import { Inter } from 'next/font/google'

//const inter = Inter({ subsets: ['latin'] })

import Header from "./Components/Header"
import './globals.css'

export const metadata = {
  title: 'movie app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
    
      {/* header */}
      <Header/>
      {/* navbar */}
      {/* search bar */}
      {children}
      </body>
    </html>
  )
}
